apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hr-dashboard

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/hpa.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - ml-service/deployment.yaml
  - ml-service/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: hr-dashboard
  app.kubernetes.io/managed-by: kustomize
