apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: hr-dashboard
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
